#
# Reduce the size of the `vendor` directory excluding unused packages, tests and
# other files that aren't needed.
#
[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"
