#
# Copyright (c) 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file contains an OpenShift template that creates all the objects needed
# for a working installation of the application. See the `template.sh` file for
# an example of how to use it.

---

apiVersion: v1
kind: Template
metadata:
  name: unified-hybrid-cloud-portal
  annotations:
    description: "Unified Hybrid Cloud Portal"

parameters:

- name: BUILD_ID
  description: The identifier of the build.

- name: BUILD_TS
  description: The timestamp of the build.

- name: GATEWAY_DOMAIN
  description: The DNS domain where the API gateway is deployed.

- name: PORTAL_DOMAIN
  description: The DNS domain where the portal will be deployed.

- name: IMAGE_PULL_POLICY
  description: Image pull policy.

- name: IMAGE
  description: Image name.

- name: IMAGE_TAG
  description: Image tag.

- name: NAMESPACE
  description: The namespace where the objects will be created.

- name: KEYCLOAK_URL
  description: The Keycloak base URL.

- name: KEYCLOAK_REALM
  description: The Keycloak realm.

- name: KEYCLOAK_CLIENT_ID
  description: The Keycloak client identifier.

- name: VERSION
  description: The version of the project.

- name: INSTALLER_URL
  description: The URL to download the installer.

objects:

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: portal-server
    labels:
      app: portal-server
  spec:
    selector:
      matchLabels:
        app: portal-server
    replicas: 1
    template:
      metadata:
        labels:
          app: portal-server
      spec:
        initContainers:
        - name: id
          image: centos:7
          command:
          - echo
          - ${VERSION}-${BUILD_ID}-${BUILD_TS}
        containers:
        - name: server
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          command:
          - /usr/local/bin/portal
          - server
          - --portal-domain=${PORTAL_DOMAIN}
          - --gateway-domain=${GATEWAY_DOMAIN}
          - --keycloak-realm=${KEYCLOAK_REALM}
          - --keycloak-client-id=${KEYCLOAK_CLIENT_ID}
          - --keycloak-url=${KEYCLOAK_URL}
          - --installer-url=${INSTALLER_URL}

- apiVersion: v1
  kind: Service
  metadata:
    name: portal-server
    labels:
      app: portal-server
  spec:
    selector:
      app: portal-server
    ports:
    - port: 8000
      targetPort: 8000
