---
# BushSlicer framework configuration overrides/additions.
# Should go into verification-tests/private/config/config.yaml
# (instead of cucushift-internal repo normally checked out at verification-tests/private)

# environment chosen by BUSHSLICER_DEFAULT_ENVIRONMENT env var
environments:
  ocm_local_dev:
    web_console_url: https://qa.foo.redhat.com:1337/openshift/
    type: OCMEnvironment
    static_users_map:
      # Actual auth to API replaced by `backend` proxy using offline token.
      # The UI will redirect login to sso.qa.redhat.com,
      # which accepts various user names all with `redhat` password.
      regularUser: "redhat:redhat"
  ocm_stage:
    web_console_url: https://qaprodauth.cloud.redhat.com/openshift/
    type: OCMEnvironment
    #static_users_map:
    #  regularUser: "YOU.openshift:PASSWORD"
  ocm_prod:
    web_console_url: https://cloud.redhat.com/openshift/
    type: OCMEnvironment
    #static_users_map:
    #  regularUser: "YOU.openshift:PASSWORD"

global:
  browser: chrome
  selenium_url: http://localhost:4444/wd/hub
